name: admix-kit-jf
channels:
    - conda-forge
    - bioconda
    - defaults
dependencies:
    - pip
    - matplotlib
    - dask
    - natsort
    - scanpy
    - statsmodels
    - xarray
    - yaml
    - zarr
    - cmake
    - pybind11
    - Cython
    - pytest
    - pip:
      - tinygwas
      - haptools
      - admix-kit
