name: docs
channels:
  - conda-forge
  - defaults
dependencies:
  - black
  - coverage
  - flake8
  - graphviz
  - heapdict
  - ipykernel
  - ipython
  - isort==4.3.21
  - multipledispatch
  - mypy
  - nbsphinx
  - nomkl
  - nose
  - numba
  - numpy
  - numpydoc
  - pandas
  - pandoc
  - psutil
  - pytest
  - pytest-cov
  - pytest-mock
  - python=3.7
  - sortedcontainers
  - scikit-learn>=0.23.1
  - scipy
  - sparse
  - sphinx==1.8.5
  - sphinx_rtd_theme
  - sphinx-gallery
  - testpath<0.4
  - tornado
  - toolz
  - xgboost
  - zict
  - pip