name: Conda environment

on: [push]

jobs:
  create-env:
    name: ${{ matrix.os }} 
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]

    steps:
      - name: checkout repository
        uses: actions/checkout@v2

      - name: create environment with mamba
        uses: conda-incubator/setup-miniconda@v2
        with:
          mamba-version: "*"
          channels: conda-forge,bioconda,defaults
          auto-activate-base: false
          activate-environment: admix-kit
          environment-file: environment.yaml

      - name: check solution
        run: |
          mamba env export
    
      - name: test admix-kit
        run: |
          pytest -sv