name: Documentation

on: [push]

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Setup Conda Environment
      uses: conda-incubator/setup-miniconda@v2
      with:
        miniconda-version: "latest"
        environment-file: docs/environment.yaml
        activate-environment: docs
        auto-activate-base: false

    - name: Install pacakge
      shell: bash -l {0}
      run: |
        python -m pip install -r requirements.txt
        python -m pip install -e .

    - name: Build docs
      shell: bash -l {0}
      run: |
        cd docs
        make html

    - name: Deploy docs
      uses: JamesIves/github-pages-deploy-action@4.1.5
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BRANCH: gh-pages
        FOLDER: docs/_build/html
        CLEAN: true
        single-commit: true

    # - name: Install dependencies
    #   run: |
    #     python -m pip install --upgrade pip
    #     
    #     pip install -e .
    #     conda install -c conda-forge pandoc

    # - name: Build documentation and update pages
    #   env:
    #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    #   run: |
    #     bash docs/build_docs.sh

