name: Sphinx document

on: [push]

jobs:
  build:
    name: Push Sphinx Pages
    strategy:
      matrix:
        python-version: [ 3.8 ]
    runs-on: ubuntu-latest
    container: debian:buster-slim
    steps:
    - name: prereq
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        apt-get update
        apt-get install -y git
        git clone "https://token:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git" .
      shell: bash

    - name: Execute script to build our documentation and update pages
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        ls -lh docs/build_docs.sh
        bash docs/build_docs.sh